### ISSUE TITLE
Typo in owm.py line 395  (self.uits -> self.units)

### ISSUE THREAD

**Issue by eagleco** [bpaauwe/udi-owm-poly#1]
![image](https://user-images.githubusercontent.com/39813792/57319074-9d78b780-70b0-11e9-8303-465c38e477ed.png)

**Comment by eagleco** [comment]
Another one: 

Looks like metric here should be imperial, line 424
![image](https://user-images.githubusercontent.com/39813792/57321981-580bb880-70b7-11e9-9838-b83d8dc43f1d.png)

**Comment by bpaauwe** [comment]
refactored the unit handling code so that these issues no longer exist.

Thanks.
