### ISSUE TITLE
Chance of precipitation = 0 or 1

### ISSUE THREAD

**Issue by pmallery** [bpaauwe/udi-owm-poly#12]
Thanks for this--very helpful.  The confusion/glitch:

The chance of precipitation is showing up as 0% or 1%.  Comparing it to the openweathermaps website for my location, it appears that low probabilities (I hypothesize <50%) are showing up as 0%, and high probabilities (I hypothesize >=50%) are showing up a 1%.  I'm guessing  they are returning a chance (probability, number between 0 and 1) and it is being rounded to a percent (0% or 1%).

**Comment by bpaauwe** [comment]
Your guess was correct.  I guess I never looked closely at what was being returned by the API.  Fixed in version 3.0.1 that should be available in the store shortly.
