### ISSUE TITLE
Not tracking temperature?

### ISSUE THREAD

**Issue by sjpbailey** [bpaauwe/udi-owm-poly#13]
Bob,
 I have had this installed for over a year and it is giving me the wrong temperature and conditions?
It is 86F outside and the OWN is showing 69 deg F.
settings are as follows.
I am in Tracy Ca
lat=37.74&lon=-121.43 elevation and forecast days 0.
Hopefully it is just a problem with the site the only reason I noticed at all is I am using it to lock out cooling based on OSA temperature and I was getting hot in the house lol!
I use this for irrigation temp, wind speed and humidity also for conditions in most of the AC programming.

**Comment by bpaauwe** [comment]
When I use that location, the data seems reasonable for me.  It's showing 82F at about 11am which seems reasonable as it's 86 here in Sacramento.

Is there (or was there) any info the log at that time?  If the node server crashed for some reason, the value would then not get updated.

**Comment by sjpbailey** [comment]
Very well a glitz from the local site that is now showing 95 deg
Just checking to see if you had any problems on your end and no poly was up so its solid.
Sorry to bug you lol it is my primary Outside Air Input to all programs.
