### ISSUE TITLE
Open Weather Map API 2.5 has been deprecated

### ISSUE THREAD

**Issue by whittedb** [bpaauwe/udi-owm-poly#16]
Do you have any plans to update this poly to use the new Open Weather Map 3.0 API?  It is currently unusable in this state.

**Comment by bpaauwe** [comment]
Not this version.  This was for PG2 which was deprecated years ago.

The PG3 OpenWeatherMap plug-in only works with the One Call 3.0 API and has since April of 2024.

**Comment by whittedb** [comment]
Ok, thanks.  I guess I'm being forced to upgrade to PG3 now.
