### ISSUE TITLE
132% clouds?

### ISSUE THREAD

**Issue by macjeff** [bpaauwe/udi-owm-poly#4]
See screenshot

Can you please explain?

thanks!!

<img width="1331" alt="Screen Shot 2020-03-03 at 9 33 10 AM" src="https://user-images.githubusercontent.com/20373758/75785883-6dcb2800-5d32-11ea-969f-daccce4edf3f.png">

**Comment by bpaauwe** [comment]
Nope, I can't. You'd have to ask OpenWeatherMap. I'm just reporting the data they provide.

**Comment by macjeff** [comment]
OK   Thought you might be doing a calculation that had an error.  I am going to go enjoy the 132% clouds!!!   LOL  You can close this.
