### ISSUE TITLE
Node Server not showing up

### ISSUE THREAD

**Issue by whittedb** [bpaauwe/udi-owm-poly#5]
I'm trying to install the node server on Polisy and even though the log says it has started and is happy with all the configuration parameters and that it is adding the nodes, I don't see anything in the admin console.

Are you sending the profile information to ISY?

**Comment by bpaauwe** [comment]
Yes, but no.  That's not a function of the node server. Polyglot manages sending the profile files to the ISY and creating the nodes there.

It isn't very good about it though.  If it thinks it sent the data then it won't check or try to send it again.  So if something went wrong when it first started, you may have to delete the node server and re-add it.

**Comment by whittedb** [comment]
Thanks, I had forgotten how finicky Polyglot was about the profile updates.  Finally got it to work after removing a node server that I was working on, uninstalling/re-installing, etc, etc.
